update github workflow, fix install, add lastest back in as seporate file, update readme

diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -1,35 +1,71 @@
 #!/usr/bin/env bash
-set -euo pipefail
 
-local_version="$1"
-install_path="$2"
+set -e
+set -o pipefail
 
-os_name="$(uname -s)"
-case "${os_name}" in
-    Linux*)     os=linux;;
-    Darwin*)    os=darwin;;
-    CYGWIN*)    os=windows;;
-    MINGW*)     os=windows;;
-    *)          echo "unknown OS"; exit 1;;
-esac
+ASDF_INSTALL_TYPE=${ASDF_INSTALL_TYPE:-version  }
+[ -n "$ASDF_INSTALL_VERSION" ] || (>&2 echo 'Missing ASDF_INSTALL_VERSION' && exit 1)
+[ -n "$ASDF_INSTALL_PATH" ] || (>&2 echo 'Missing ASDF_INSTALL_PATH' && exit 1)
 
-case "$(uname -m)" in
-    x86_64*)    arch=amd64;;
-    arm64*)     arch=arm64;;
-    *)          echo "unknown architecture"; exit 1;;
-esac
+install_crictl() {
+  local install_type=$1
+  local version=$2
+  local install_path=$3
+  local bin_install_path="$install_path/bin"
 
-tmpdir="$(mktemp -d)"
+  local download_url="$(get_download_url $version)"
+  local platform="$(get_arch)"
 
-pushd "$tmpdir" >/dev/null
+  mkdir -p "${bin_install_path}"
 
-binary_url="https://github.com/kubernetes-sigs/cri-tools/releases/download/v${local_version}/crictl-v${local_version}-${os}-${arch}.tar.gz"
-curl -L -o "crictl.tar.gz" "$binary_url"
+  if [ "$TMPDIR" = "" ]; then
+    local tmp_download_dir=$(mktemp -d -t crictl_XXXXXX)
+  else
+    local tmp_download_dir=$TMPDIR
+  fi
 
-tar xzf "crictl.tar.gz"
+  local download_path="$tmp_download_dir/crictl.tar.gz"
 
-mv "crictl" "$install_path/bin/crictl"
+  echo "Downloading crictl from ${download_url} to ${download_path}"
+  curl -Lo $download_path $download_url
 
-popd >/dev/null
+  echo "Creating bin directory"
+  mkdir -p "${bin_install_path}"
 
-rm -rf "$tmpdir"
+  echo "Cleaning previous binaries"
+  rm -f $binary_path 2>/dev/null || true
+
+  echo "Copying binary"
+  tar -zxf ${download_path} --directory $tmp_download_dir
+  cp ${tmp_download_dir}/crictl ${bin_install_path}
+  chmod +x ${bin_install_path}/crictl
+  echo "crictl ${version}" >> ~/.tool-versions
+}
+
+get_arch() {
+  uname | tr '[:upper:]' '[:lower:]'
+}
+
+get_cpu() {
+  local machine_hardware_name
+  machine_hardware_name=${ASDF_crictl_OVERWRITE_ARCH:-"$(uname -m)"}
+
+  case "$machine_hardware_name" in
+    'x86_64') local cpu_type="amd64";;
+    'powerpc64le' | 'ppc64le') local cpu_type="ppc64le";;    
+    'aarch64') local cpu_type="arm64";;
+    'armv7l') local cpu_type="arm";;
+    *) local cpu_type="$machine_hardware_name";;
+  esac
+
+  echo "$cpu_type"
+}
+
+get_download_url() {
+  local version="$1"
+  local platform="$(get_arch)"
+  echo "https://github.com/kubernetes-sigs/cri-tools/releases/download/v${version}/crictl-v${version}-${platform}_$(get_cpu).tar.gz"
+}
+}
+
+install_crictl $ASDF_INSTALL_TYPE $ASDF_INSTALL_VERSION $ASDF_INSTALL_PATH
